export enum HttpErrorName {
  BadRequest = "Bad Request",
  Unauthorized = "Unauthorized",
  PaymentRequired = "Payment Required",
  Forbidden = "Forbidden",
  NotFound = "Not Found",
  MethodNotAllowed = "Method Not Allowed",
  NotAcceptable = "Not Acceptable",
  ProxyAuthenticationRequired = "Proxy Authentication Required",
  RequestTimeout = "Request Timeout",
  Conflict = "Conflict",
  Gone = "Gone",
  LengthRequired = "Length Required",
  PreconditionFailed = "Precondition Failed",
  PayloadTooLarge = "Payload Too Large",
  URITooLong = "URI Too Long",
  UnsupportedMediaType = "Unsupported Media Type",
  RangeNotSatisfiable = "Range Not Satisfiable",
  ExpectationFailed = "Expectation Failed",
  ImATeapot = "I'm a teapot",
  MisdirectedRequest = "Misdirected Request",
  UnprocessableEntity = "Unprocessable Entity",
  Locked = "Locked",
  FailedDependency = "Failed Dependency",
  TooEarly = "Too Early",
  UpgradeRequired = "Upgrade Required",
  PreconditionRequired = "Precondition Required",
  TooManyRequests = "Too Many Requests",
  RequestHeaderFieldsTooLarge = "Request Header Fields Too Large",
  UnavailableForLegalReasons = "Unavailable For Legal Reasons",

  InternalServerError = "Internal Server Error",
  NotImplemented = "Not Implemented",
  BadGateway = "Bad Gateway",
  ServiceUnavailable = "Service Unavailable",
  GatewayTimeout = "Gateway Timeout",
  HTTPVersionNotSupported = "HTTP Version Not Supported",
  VariantAlsoNegotiates = "Variant Also Negotiates",
  InsufficientStorage = "Insufficient Storage",
  LoopDetected = "Loop Detected",
  NotExtended = "Not Extended",
  NetworkAuthenticationRequired = "Network Authentication Required",
}

export enum HttpStatusName {
  Continue = "Continue",
  SwitchingProtocols = "Switching Protocols",
  Processing = "Processing",
  EarlyHints = "Early Hints",

  OK = "OK",
  Created = "Created",
  Accepted = "Accepted",
  NonAuthoritativeInformation = "Non-Authoritative Information",
  NoContent = "No Content",
  ResetContent = "Reset Content",
  PartialContent = "Partial Content",
  MultiStatus = "Multi-Status",
  AlreadyReported = "Already Reported",
  IMUsed = "IM Used",

  MultipleChoices = "Multiple Choices",
  MovedPermanently = "Moved Permanently",
  Found = "Found",
  SeeOther = "See Other",
  NotModified = "Not Modified",
  UseProxy = "Use Proxy",
  TemporaryRedirect = "Temporary Redirect",
  PermanentRedirect = "Permanent Redirect",
}
