import type { Metadata } from "next"
import { AuthProvider } from "./_providers/auth.provider"
import { Poppins } from "next/font/google"
import { Toaster } from "sonner"
import "leaflet/dist/leaflet.css"
import "./globals.css"

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR" className="dark">
      <body className={`${poppins.variable} font-sans antialiased`}>
        <AuthProvider>
          <div className="flex min-h-screen flex-col">{children}</div>
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  )
}
